# Site settings
title: Lantern of Chaos
header-img: img/home-bg.jpg
description: "Blogs on visualization, Scala and more."
baseurl: ""
url: "http://saurfang.github.io"
twitter_username: saurfang86
github_username:  saurfang

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
